import {
  INITIAL_STATE as PHONE_NUMBER_LOGIN_INITIAL_STATE,
  MODEL_KEY as PHONE_NUMBER_LOGIN_MODEL_KEY,
} from 'components/molecules/Login/WithPhoneNumber';
import { AD_INITIAL_STATE, AD_FORM_MODEL_KEY } from './ad/constants';

export default {
  [AD_FORM_MODEL_KEY]: AD_INITIAL_STATE,
  [PHONE_NUMBER_LOGIN_MODEL_KEY]: PHONE_NUMBER_LOGIN_INITIAL_STATE,
};
