// flow-typed signature: 51acf92e3b658fdffdd75b2af283fd8e
// flow-typed version: <<STUB>>/firebase-server_v^0.11.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-server/bin/firebase-server' {
  declare module.exports: any;
}

declare module 'firebase-server/lib/firebaseHash' {
  declare module.exports: any;
}

declare module 'firebase-server/lib/testable-clock' {
  declare module.exports: any;
}

declare module 'firebase-server/lib/token-validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-server/bin/firebase-server.js' {
  declare module.exports: $Exports<'firebase-server/bin/firebase-server'>;
}
declare module 'firebase-server/index' {
  declare module.exports: $Exports<'firebase-server'>;
}
declare module 'firebase-server/index.js' {
  declare module.exports: $Exports<'firebase-server'>;
}
declare module 'firebase-server/lib/firebaseHash.js' {
  declare module.exports: $Exports<'firebase-server/lib/firebaseHash'>;
}
declare module 'firebase-server/lib/testable-clock.js' {
  declare module.exports: $Exports<'firebase-server/lib/testable-clock'>;
}
declare module 'firebase-server/lib/token-validator.js' {
  declare module.exports: $Exports<'firebase-server/lib/token-validator'>;
}
