// flow-typed signature: 29e313b97fbe8f1535fb551ddb327831
// flow-typed version: <<STUB>>/firebase-server_v^0.12.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-server/bin/firebase-server' {
  declare module.exports: any;
}

declare module 'firebase-server/lib/firebase-hash' {
  declare module.exports: any;
}

declare module 'firebase-server/lib/http-server' {
  declare module.exports: any;
}

declare module 'firebase-server/lib/testable-clock' {
  declare module.exports: any;
}

declare module 'firebase-server/lib/token-validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-server/bin/firebase-server.js' {
  declare module.exports: $Exports<'firebase-server/bin/firebase-server'>;
}
declare module 'firebase-server/index' {
  declare module.exports: $Exports<'firebase-server'>;
}
declare module 'firebase-server/index.js' {
  declare module.exports: $Exports<'firebase-server'>;
}
declare module 'firebase-server/lib/firebase-hash.js' {
  declare module.exports: $Exports<'firebase-server/lib/firebase-hash'>;
}
declare module 'firebase-server/lib/http-server.js' {
  declare module.exports: $Exports<'firebase-server/lib/http-server'>;
}
declare module 'firebase-server/lib/testable-clock.js' {
  declare module.exports: $Exports<'firebase-server/lib/testable-clock'>;
}
declare module 'firebase-server/lib/token-validator.js' {
  declare module.exports: $Exports<'firebase-server/lib/token-validator'>;
}
