// flow-typed signature: d2e76eeb22d759b84f898dce10ee4466
// flow-typed version: <<STUB>>/react-spinner-material_v^1.0.16/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinner-material'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinner-material' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinner-material/lib/index' {
  declare module.exports: any;
}

declare module 'react-spinner-material/lib/utils' {
  declare module.exports: any;
}

declare module 'react-spinner-material/render' {
  declare module.exports: any;
}

declare module 'react-spinner-material/src/index' {
  declare module.exports: any;
}

declare module 'react-spinner-material/src/utils' {
  declare module.exports: any;
}

declare module 'react-spinner-material/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spinner-material/lib/index.js' {
  declare module.exports: $Exports<'react-spinner-material/lib/index'>;
}
declare module 'react-spinner-material/lib/utils.js' {
  declare module.exports: $Exports<'react-spinner-material/lib/utils'>;
}
declare module 'react-spinner-material/render.js' {
  declare module.exports: $Exports<'react-spinner-material/render'>;
}
declare module 'react-spinner-material/src/index.js' {
  declare module.exports: $Exports<'react-spinner-material/src/index'>;
}
declare module 'react-spinner-material/src/utils.js' {
  declare module.exports: $Exports<'react-spinner-material/src/utils'>;
}
declare module 'react-spinner-material/webpack.config.js' {
  declare module.exports: $Exports<'react-spinner-material/webpack.config'>;
}
