// flow-typed signature: 3d09148ea3efc8c5fba621b85a2b0ae9
// flow-typed version: <<STUB>>/react-masonry-infinite_v^1.2.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-masonry-infinite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-masonry-infinite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-masonry-infinite/lib/index' {
  declare module.exports: any;
}

declare module 'react-masonry-infinite/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-masonry-infinite/lib/index.js' {
  declare module.exports: $Exports<'react-masonry-infinite/lib/index'>;
}
declare module 'react-masonry-infinite/src/index.js' {
  declare module.exports: $Exports<'react-masonry-infinite/src/index'>;
}
