// flow-typed signature: 3e913a3999e08fcfba6042f07afe55bd
// flow-typed version: <<STUB>>/react-telephone-input_v^4.2.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-telephone-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-telephone-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-telephone-input/es/ReactTelephoneInput' {
  declare module.exports: any;
}

declare module 'react-telephone-input/es/withStyles' {
  declare module.exports: any;
}

declare module 'react-telephone-input/lib/ReactTelephoneInput' {
  declare module.exports: any;
}

declare module 'react-telephone-input/lib/withStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-telephone-input/es/ReactTelephoneInput.js' {
  declare module.exports: $Exports<'react-telephone-input/es/ReactTelephoneInput'>;
}
declare module 'react-telephone-input/es/withStyles.js' {
  declare module.exports: $Exports<'react-telephone-input/es/withStyles'>;
}
declare module 'react-telephone-input/lib/ReactTelephoneInput.js' {
  declare module.exports: $Exports<'react-telephone-input/lib/ReactTelephoneInput'>;
}
declare module 'react-telephone-input/lib/withStyles.js' {
  declare module.exports: $Exports<'react-telephone-input/lib/withStyles'>;
}
