// flow-typed signature: 32d95cce881a731aaab8bca05d08f100
// flow-typed version: <<STUB>>/react-phone-input_v^1.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-phone-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-phone-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-phone-input/dist/index' {
  declare module.exports: any;
}

declare module 'react-phone-input/src/country_data' {
  declare module.exports: any;
}

declare module 'react-phone-input/src/index' {
  declare module.exports: any;
}

declare module 'react-phone-input/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-phone-input/dist/index.js' {
  declare module.exports: $Exports<'react-phone-input/dist/index'>;
}
declare module 'react-phone-input/src/country_data.js' {
  declare module.exports: $Exports<'react-phone-input/src/country_data'>;
}
declare module 'react-phone-input/src/index.js' {
  declare module.exports: $Exports<'react-phone-input/src/index'>;
}
declare module 'react-phone-input/webpack.config.js' {
  declare module.exports: $Exports<'react-phone-input/webpack.config'>;
}
