// flow-typed signature: 628f09ed0a812c79bf08890afef8a91c
// flow-typed version: <<STUB>>/react-imgix_v^7.1.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-imgix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-imgix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-imgix/es/array-findindex' {
  declare module.exports: any;
}

declare module 'react-imgix/es/index' {
  declare module.exports: any;
}

declare module 'react-imgix/es/index.test' {
  declare module.exports: any;
}

declare module 'react-imgix/es/support' {
  declare module.exports: any;
}

declare module 'react-imgix/lib/array-findindex' {
  declare module.exports: any;
}

declare module 'react-imgix/lib/index' {
  declare module.exports: any;
}

declare module 'react-imgix/lib/index.test' {
  declare module.exports: any;
}

declare module 'react-imgix/lib/support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-imgix/es/array-findindex.js' {
  declare module.exports: $Exports<'react-imgix/es/array-findindex'>;
}
declare module 'react-imgix/es/index.js' {
  declare module.exports: $Exports<'react-imgix/es/index'>;
}
declare module 'react-imgix/es/index.test.js' {
  declare module.exports: $Exports<'react-imgix/es/index.test'>;
}
declare module 'react-imgix/es/support.js' {
  declare module.exports: $Exports<'react-imgix/es/support'>;
}
declare module 'react-imgix/lib/array-findindex.js' {
  declare module.exports: $Exports<'react-imgix/lib/array-findindex'>;
}
declare module 'react-imgix/lib/index.js' {
  declare module.exports: $Exports<'react-imgix/lib/index'>;
}
declare module 'react-imgix/lib/index.test.js' {
  declare module.exports: $Exports<'react-imgix/lib/index.test'>;
}
declare module 'react-imgix/lib/support.js' {
  declare module.exports: $Exports<'react-imgix/lib/support'>;
}
