// flow-typed signature: d3328c0f1e2a3de00f0d9bfc66dcf341
// flow-typed version: <<STUB>>/redux-cli_v^1.9.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-cli/bin/redux-g' {
  declare module.exports: any;
}

declare module 'redux-cli/bin/redux-generate' {
  declare module.exports: any;
}

declare module 'redux-cli/bin/redux-init' {
  declare module.exports: any;
}

declare module 'redux-cli/bin/redux-new' {
  declare module.exports: any;
}

declare module 'redux-cli/bin/redux' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/blueprint/files/blueprints/__name__/index' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/blueprint/index' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/duck/files/__root__/__duck__/__name__' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/duck/files/__test__/redux/modules/__name__.test' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/duck/index' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/dumb/files/__root__/__dumb__/__name__' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/dumb/files/__test__/__dumb__/__name__.test' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/dumb/index' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/form/files/__root__/forms/__name__' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/form/files/__test__/forms/__name__.test' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/form/index' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/smart/files/__root__/__smart__/__name__' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/smart/files/__test__/__smart__/__name__.test' {
  declare module.exports: any;
}

declare module 'redux-cli/blueprints/smart/index' {
  declare module.exports: any;
}

declare module 'redux-cli/coverage/prettify' {
  declare module.exports: any;
}

declare module 'redux-cli/coverage/sorter' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/cli/index' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/cli/redux-generate' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/cli/redux-init' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/cli/redux-new' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/config' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/models/blueprint' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/models/file-info' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/models/project-settings' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/models/sub-command' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/models/task' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/models/ui' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/prompts/initPrompt' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/prompts/setup' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/sub-commands/generate' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/sub-commands/init' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/sub-commands/new' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/tasks/create-and-step-into-directory' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/tasks/generate-from-blueprint' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/tasks/git-pull' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/util/fs' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/util/mixin' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/util/text-helper' {
  declare module.exports: any;
}

declare module 'redux-cli/lib/version' {
  declare module.exports: any;
}

declare module 'redux-cli/test/fixtures/blueprints/basic/files/expected-file' {
  declare module.exports: any;
}

declare module 'redux-cli/test/fixtures/blueprints/basic/index' {
  declare module.exports: any;
}

declare module 'redux-cli/test/helpers/fs-helpers' {
  declare module.exports: any;
}

declare module 'redux-cli/test/helpers/mock-settings' {
  declare module.exports: any;
}

declare module 'redux-cli/test/helpers/mock-ui' {
  declare module.exports: any;
}

declare module 'redux-cli/test/models/blueprint.test' {
  declare module.exports: any;
}

declare module 'redux-cli/test/models/file-info.test' {
  declare module.exports: any;
}

declare module 'redux-cli/test/models/project-settings.test' {
  declare module.exports: any;
}

declare module 'redux-cli/test/models/sub-command.test' {
  declare module.exports: any;
}

declare module 'redux-cli/test/models/task.test' {
  declare module.exports: any;
}

declare module 'redux-cli/test/models/ui.test' {
  declare module.exports: any;
}

declare module 'redux-cli/test/prompts/setup.test' {
  declare module.exports: any;
}

declare module 'redux-cli/test/setup' {
  declare module.exports: any;
}

declare module 'redux-cli/test/util/fs.test' {
  declare module.exports: any;
}

declare module 'redux-cli/test/util/mixin.test' {
  declare module.exports: any;
}

declare module 'redux-cli/test/util/text-helper.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-cli/bin/redux-g.js' {
  declare module.exports: $Exports<'redux-cli/bin/redux-g'>;
}
declare module 'redux-cli/bin/redux-generate.js' {
  declare module.exports: $Exports<'redux-cli/bin/redux-generate'>;
}
declare module 'redux-cli/bin/redux-init.js' {
  declare module.exports: $Exports<'redux-cli/bin/redux-init'>;
}
declare module 'redux-cli/bin/redux-new.js' {
  declare module.exports: $Exports<'redux-cli/bin/redux-new'>;
}
declare module 'redux-cli/bin/redux.js' {
  declare module.exports: $Exports<'redux-cli/bin/redux'>;
}
declare module 'redux-cli/blueprints/blueprint/files/blueprints/__name__/index.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/blueprint/files/blueprints/__name__/index'>;
}
declare module 'redux-cli/blueprints/blueprint/index.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/blueprint/index'>;
}
declare module 'redux-cli/blueprints/duck/files/__root__/__duck__/__name__.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/duck/files/__root__/__duck__/__name__'>;
}
declare module 'redux-cli/blueprints/duck/files/__test__/redux/modules/__name__.test.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/duck/files/__test__/redux/modules/__name__.test'>;
}
declare module 'redux-cli/blueprints/duck/index.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/duck/index'>;
}
declare module 'redux-cli/blueprints/dumb/files/__root__/__dumb__/__name__.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/dumb/files/__root__/__dumb__/__name__'>;
}
declare module 'redux-cli/blueprints/dumb/files/__test__/__dumb__/__name__.test.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/dumb/files/__test__/__dumb__/__name__.test'>;
}
declare module 'redux-cli/blueprints/dumb/index.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/dumb/index'>;
}
declare module 'redux-cli/blueprints/form/files/__root__/forms/__name__.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/form/files/__root__/forms/__name__'>;
}
declare module 'redux-cli/blueprints/form/files/__test__/forms/__name__.test.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/form/files/__test__/forms/__name__.test'>;
}
declare module 'redux-cli/blueprints/form/index.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/form/index'>;
}
declare module 'redux-cli/blueprints/smart/files/__root__/__smart__/__name__.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/smart/files/__root__/__smart__/__name__'>;
}
declare module 'redux-cli/blueprints/smart/files/__test__/__smart__/__name__.test.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/smart/files/__test__/__smart__/__name__.test'>;
}
declare module 'redux-cli/blueprints/smart/index.js' {
  declare module.exports: $Exports<'redux-cli/blueprints/smart/index'>;
}
declare module 'redux-cli/coverage/prettify.js' {
  declare module.exports: $Exports<'redux-cli/coverage/prettify'>;
}
declare module 'redux-cli/coverage/sorter.js' {
  declare module.exports: $Exports<'redux-cli/coverage/sorter'>;
}
declare module 'redux-cli/lib/cli/index.js' {
  declare module.exports: $Exports<'redux-cli/lib/cli/index'>;
}
declare module 'redux-cli/lib/cli/redux-generate.js' {
  declare module.exports: $Exports<'redux-cli/lib/cli/redux-generate'>;
}
declare module 'redux-cli/lib/cli/redux-init.js' {
  declare module.exports: $Exports<'redux-cli/lib/cli/redux-init'>;
}
declare module 'redux-cli/lib/cli/redux-new.js' {
  declare module.exports: $Exports<'redux-cli/lib/cli/redux-new'>;
}
declare module 'redux-cli/lib/config.js' {
  declare module.exports: $Exports<'redux-cli/lib/config'>;
}
declare module 'redux-cli/lib/models/blueprint.js' {
  declare module.exports: $Exports<'redux-cli/lib/models/blueprint'>;
}
declare module 'redux-cli/lib/models/file-info.js' {
  declare module.exports: $Exports<'redux-cli/lib/models/file-info'>;
}
declare module 'redux-cli/lib/models/project-settings.js' {
  declare module.exports: $Exports<'redux-cli/lib/models/project-settings'>;
}
declare module 'redux-cli/lib/models/sub-command.js' {
  declare module.exports: $Exports<'redux-cli/lib/models/sub-command'>;
}
declare module 'redux-cli/lib/models/task.js' {
  declare module.exports: $Exports<'redux-cli/lib/models/task'>;
}
declare module 'redux-cli/lib/models/ui.js' {
  declare module.exports: $Exports<'redux-cli/lib/models/ui'>;
}
declare module 'redux-cli/lib/prompts/initPrompt.js' {
  declare module.exports: $Exports<'redux-cli/lib/prompts/initPrompt'>;
}
declare module 'redux-cli/lib/prompts/setup.js' {
  declare module.exports: $Exports<'redux-cli/lib/prompts/setup'>;
}
declare module 'redux-cli/lib/sub-commands/generate.js' {
  declare module.exports: $Exports<'redux-cli/lib/sub-commands/generate'>;
}
declare module 'redux-cli/lib/sub-commands/init.js' {
  declare module.exports: $Exports<'redux-cli/lib/sub-commands/init'>;
}
declare module 'redux-cli/lib/sub-commands/new.js' {
  declare module.exports: $Exports<'redux-cli/lib/sub-commands/new'>;
}
declare module 'redux-cli/lib/tasks/create-and-step-into-directory.js' {
  declare module.exports: $Exports<'redux-cli/lib/tasks/create-and-step-into-directory'>;
}
declare module 'redux-cli/lib/tasks/generate-from-blueprint.js' {
  declare module.exports: $Exports<'redux-cli/lib/tasks/generate-from-blueprint'>;
}
declare module 'redux-cli/lib/tasks/git-pull.js' {
  declare module.exports: $Exports<'redux-cli/lib/tasks/git-pull'>;
}
declare module 'redux-cli/lib/util/fs.js' {
  declare module.exports: $Exports<'redux-cli/lib/util/fs'>;
}
declare module 'redux-cli/lib/util/mixin.js' {
  declare module.exports: $Exports<'redux-cli/lib/util/mixin'>;
}
declare module 'redux-cli/lib/util/text-helper.js' {
  declare module.exports: $Exports<'redux-cli/lib/util/text-helper'>;
}
declare module 'redux-cli/lib/version.js' {
  declare module.exports: $Exports<'redux-cli/lib/version'>;
}
declare module 'redux-cli/test/fixtures/blueprints/basic/files/expected-file.js' {
  declare module.exports: $Exports<'redux-cli/test/fixtures/blueprints/basic/files/expected-file'>;
}
declare module 'redux-cli/test/fixtures/blueprints/basic/index.js' {
  declare module.exports: $Exports<'redux-cli/test/fixtures/blueprints/basic/index'>;
}
declare module 'redux-cli/test/helpers/fs-helpers.js' {
  declare module.exports: $Exports<'redux-cli/test/helpers/fs-helpers'>;
}
declare module 'redux-cli/test/helpers/mock-settings.js' {
  declare module.exports: $Exports<'redux-cli/test/helpers/mock-settings'>;
}
declare module 'redux-cli/test/helpers/mock-ui.js' {
  declare module.exports: $Exports<'redux-cli/test/helpers/mock-ui'>;
}
declare module 'redux-cli/test/models/blueprint.test.js' {
  declare module.exports: $Exports<'redux-cli/test/models/blueprint.test'>;
}
declare module 'redux-cli/test/models/file-info.test.js' {
  declare module.exports: $Exports<'redux-cli/test/models/file-info.test'>;
}
declare module 'redux-cli/test/models/project-settings.test.js' {
  declare module.exports: $Exports<'redux-cli/test/models/project-settings.test'>;
}
declare module 'redux-cli/test/models/sub-command.test.js' {
  declare module.exports: $Exports<'redux-cli/test/models/sub-command.test'>;
}
declare module 'redux-cli/test/models/task.test.js' {
  declare module.exports: $Exports<'redux-cli/test/models/task.test'>;
}
declare module 'redux-cli/test/models/ui.test.js' {
  declare module.exports: $Exports<'redux-cli/test/models/ui.test'>;
}
declare module 'redux-cli/test/prompts/setup.test.js' {
  declare module.exports: $Exports<'redux-cli/test/prompts/setup.test'>;
}
declare module 'redux-cli/test/setup.js' {
  declare module.exports: $Exports<'redux-cli/test/setup'>;
}
declare module 'redux-cli/test/util/fs.test.js' {
  declare module.exports: $Exports<'redux-cli/test/util/fs.test'>;
}
declare module 'redux-cli/test/util/mixin.test.js' {
  declare module.exports: $Exports<'redux-cli/test/util/mixin.test'>;
}
declare module 'redux-cli/test/util/text-helper.test.js' {
  declare module.exports: $Exports<'redux-cli/test/util/text-helper.test'>;
}
