# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.6.0-browsers
        environment:
          - DBUS_SESSION_BUS_ADDRESS: /dev/null

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "backend/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Install /functions dependencies
          command: cd backend && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - functions/node_modules
          key: v1-dependencies-{{ checksum "backend/package.json" }}

      - run:
          name: Start app
          command: yarn start:ui
          background: true

      - run:
          name: Run lint
          command: yarn lint

      - run:
          name: Run unit tests
          command: yarn test:unit

      - run:
          name: Run end-to-end tests
          command: yarn setup:e2e && yarn test:e2e

      - deploy:
          name: Deploy master to Firebase Hosting
          command: yarn deploy --token=$FIREBASE_TOKEN --non-interactive
