version: 2

references:
    workspace_root: &workspace_root
      ~/repo

    attach_workspace: &attach_workspace
      attach_workspace:
        at: *workspace_root

defaults: &defaults
  docker:
    - image: circleci/node:8.6.0-browsers
      environment:
        - DBUS_SESSION_BUS_ADDRESS: /dev/null
  working_directory: *workspace_root

development_branches: &development_branches
  only:
    - dev
    - /^feat\/.*/

production_branches: &production_branches
  only:
    - master

deployment_branches: &deployment_branches
  only:
    - dev
    - /^feat\/.*/
    - master

jobs:
  # Install dependencies
  setup:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Fetch submodules
          command: git submodule update --init --recursive

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
          - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-packages-{{ .Branch }}
          - yarn-packages-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run lint
          command: yarn lint

  unit_test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run unit tests
          command: yarn test:web

  e2e_test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Start app
          command: yarn start:ui
          background: true

      - run:
          name: Run end-to-end tests
          command: yarn setup:e2e && yarn test:e2e

  deploy_development:
    <<: *defaults
    steps:
      - *attach_workspace

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Switch to development project
          command: yarn firebase use development

      - deploy:
          name: Deploy to Development environment
          command: CI=false yarn deploy --token=$FIREBASE_TOKEN --non-interactive

      - save_cache:
          paths:
            - build/functions/node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

  deploy_production:
    <<: *defaults
    steps:
      - *attach_workspace

      - run:
          name: Use production .env and serviceAccountKey
          command: git clone git@bitbucket.org:pesposa/secrets.git secrets && mv -f ./secrets/.env.production ./.env && mv -f ./secrets/serviceAccountKeys/production.json ./packages/core/src/config/serviceAccountKey.json

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Switch to production project
          command: yarn firebase use production

      - deploy:
          name: Deploy to Production environment
          command: CI=false yarn deploy --token=$FIREBASE_TOKEN --non-interactive

      - save_cache:
          paths:
            - build/functions/node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  main:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - unit_test:
          requires:
            - setup
      - e2e_test:
          requires:
            - setup
          filters:
            branches: *deployment_branches
      - deploy_development:
          requires:
            - lint
            # - unit_test
            # - e2e_test
          filters:
            branches: *development_branches
      - deploy_production:
          requires:
            - lint
            # - unit_test
            # - e2e_test
          filters:
            branches: *production_branches
