// flow-typed signature: 75b110451f54540cdd25cb4877b54200
// flow-typed version: <<STUB>>/lodash.round_v^4.0.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.round'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.round' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.round/index' {
  declare module.exports: $Exports<'lodash.round'>;
}
declare module 'lodash.round/index.js' {
  declare module.exports: $Exports<'lodash.round'>;
}
