// flow-typed signature: 141fefa88acdf736d8f9f5d94add90ee
// flow-typed version: <<STUB>>/react-script-loader-hoc_v^1.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-script-loader-hoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-script-loader-hoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-script-loader-hoc/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-script-loader-hoc/dist/index.js' {
  declare module.exports: $Exports<'react-script-loader-hoc/dist/index'>;
}
