export const AD_CREATE_PENDING = 'postAd/AD_CREATE_PENDING';
export const AD_CREATE_FAILED = 'postAd/AD_CREATE_FAILED';
export const AD_CREATE_COMPLETED = 'postAd/AD_CREATE_COMPLETED';
export const AD_CREATE_RESET = 'postAd/AD_CREATE_RESET';
