export const SEARCH_REQUEST_STARTED = 'search/SEARCH_REQUEST_STARTED';
export const SEARCH_REQUEST_SUCCEEDED = 'search/SEARCH_REQUEST_SUCCEEDED';
export const SEARCH_REQUEST_FAILED = 'search/SEARCH_REQUEST_FAILED';
export const LOAD_MORE = 'search/LOAD_MORE';
